In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [6]:
df = pd.read_csv('data/train.csv',usecols=['Age','Fare','Survived'])
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(714, 3)

In [16]:
X = df.iloc[:,1:3]
y = df.iloc[:,0]

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
X_train.head(5)

      Age     Fare
328  31.0  20.5250
73   26.0  14.4542
253  30.0  16.1000
719  33.0   7.7750
666  25.0  13.0000

In [20]:
clf=DecisionTreeClassifier()

In [21]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
y_pred = clf.predict(X_test)

In [24]:
print("Before Binning",accuracy_score(y_test,y_pred))

Before Binning 0.6293706293706294

In [56]:
#Apply bining
kbin_age = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')

In [27]:
trf = ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])
])

In [28]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [34]:
trf.named_transformers_

{'first': KBinsDiscretizer(encode='ordinal', n_bins=10),
 'second': KBinsDiscretizer(encode='ordinal', n_bins=10)}

In [35]:
trf.named_transformers_['first']

KBinsDiscretizer(encode='ordinal', n_bins=10)

In [36]:
trf.named_transformers_['second']

KBinsDiscretizer(encode='ordinal', n_bins=10)

In [37]:
trf.named_transformers_['first'].bin_edges_

array([array([ 0.42, 14.  , 19.  , 22.  , 25.  , 28.5 , 32.  , 36.  , 42.  ,
              50.  , 80.  ])                                                ],
      dtype=object)

In [38]:
trf.named_transformers_['second'].bin_edges_

array([array([  0.    ,   7.75  ,   7.8958,   9.225 ,  13.    ,  15.75  ,
               26.    ,  29.125 ,  51.4792,  82.1708, 512.3292])         ],
      dtype=object)

In [39]:
output = pd.DataFrame({
    'age':X_train['Age'],
    'age_trf':X_train_trf[:,0],
    'fare':X_train['Fare'],
    'fare_trf':X_train_trf[:,1]
})

In [41]:
output.head()

      age  age_trf     fare  fare_trf
328  31.0      5.0  20.5250       5.0
73   26.0      4.0  14.4542       4.0
253  30.0      5.0  16.1000       5.0
719  33.0      6.0   7.7750       1.0
666  25.0      4.0  13.0000       4.0

In [42]:
clf.fit(X_train_trf,y_train)

DecisionTreeClassifier()

In [45]:
y_pred1 = clf.predict(X_test_trf)

In [46]:
print("Score After quantile binning",accuracy_score(y_test,y_pred1)

0.6223776223776224

### Crete Function

In [61]:

kbin_age = KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='kmeans')
kbin_fare = KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='kmeans')
    
trf =ColumnTransformer([
('first',kbin_age,[0]),
('second',kbin_fare,[1])
])
    
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)
clr = DecisionTreeClassifier()
    
clf.fit(X_train_trf,y_train)
    
y_pred2 = clf.predict(X_test_trf)
accuracy_score(y_test,y_pred2)

C:\Users\narendra tekale\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(
C:\Users\narendra tekale\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(
C:\Users\narendra tekale\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(
C:\Users\narendra tekale\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(

0.6223776223776224