In [46]:
import pandas as pd

In [47]:
df = pd.read_csv('data/boston_house_prices.csv')
df.head()

,506,13,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
1,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24
2,0.02731,0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14,21.6
3,0.02729,0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
4,0.03237,0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4

In [48]:
df = df.drop([0])

In [49]:
X = df.iloc[:,0:13]
y = df.iloc[:,13]

In [52]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score

In [54]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svr = SVR()

In [55]:
estimators = [('lr',lr),('dt',dt),('svr',svr)]

In [58]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

lr 0.2
dt -0.15
svr -0.41

In [56]:
from sklearn.ensemble import VotingRegressor

In [57]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.44

### Change the weight of each algorithm

In [59]:

for i in range(1,4):
  for j in range(1,4):
    for k in range(1,4):
      vr = VotingRegressor(estimators,weights=[i,j,k])
      scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
      print("For i={},j={},k={}".format(i,j,k),np.round(np.mean(scores),2))

For i=1,j=1,k=1 0.45
For i=1,j=1,k=2 0.35
For i=1,j=1,k=3 0.27
For i=1,j=2,k=1 0.32
For i=1,j=2,k=2 0.38
For i=1,j=2,k=3 0.35
For i=1,j=3,k=1 0.39
For i=1,j=3,k=2 0.38
For i=1,j=3,k=3 0.36
For i=2,j=1,k=1 0.45
For i=2,j=1,k=2 0.41
For i=2,j=1,k=3 0.36
For i=2,j=2,k=1 0.44
For i=2,j=2,k=2 0.4
For i=2,j=2,k=3 0.4
For i=2,j=3,k=1 0.38
For i=2,j=3,k=2 0.44
For i=2,j=3,k=3 0.41
For i=3,j=1,k=1 0.45
For i=3,j=1,k=2 0.43
For i=3,j=1,k=3 0.39
For i=3,j=2,k=1 0.44
For i=3,j=2,k=2 0.43
For i=3,j=2,k=3 0.42
For i=3,j=3,k=1 0.44
For i=3,j=3,k=2 0.45
For i=3,j=3,k=3 0.4

In [60]:

# using the same algorithm

dt1 = DecisionTreeRegressor(max_depth=1)
dt2 = DecisionTreeRegressor(max_depth=3)
dt3 = DecisionTreeRegressor(max_depth=5)
dt4 = DecisionTreeRegressor(max_depth=7)
dt5 = DecisionTreeRegressor(max_depth=None)

In [61]:
estimators = [('dt1',dt1),('dt2',dt2),('dt3',dt3),('dt4',dt4),('dt5',dt5)]

In [62]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

dt1 -0.85
dt2 -0.13
dt3 0.11
dt4 0.04
dt5 -0.07

In [63]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.14

### Practice on other dataset

In [66]:
concrete = pd.read_csv('data/concrete_data.csv')
concrete.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [67]:
concrete.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [78]:
X = concrete.drop(['Strength'],axis=1)
y = concrete['Strength']

In [81]:
X.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [82]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svr = SVR()

In [88]:
estimators =[('lr',lr),('dt',dt),('svr',svr)]

In [90]:
vc = VotingRegressor(estimators)
score = cross_val_score(vc,X,y,scoring='r2',cv=10)
np.round(np.mean(scores),2)

0.14

In [91]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

lr 0.28
dt 0.49
svr -0.08