In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('data/glass.csv')
df

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [4]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [8]:
X = df.drop(columns=['Type'])
y = df['Type']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
X_train

          RI     Na    Mg    Al     Si     K     Ca    Ba    Fe
79   1.51590  12.82  3.52  1.90  72.86  0.69   7.97  0.00  0.00
161  1.51934  13.64  3.54  0.75  72.65  0.16   8.89  0.15  0.24
109  1.51818  13.72  0.00  0.56  74.45  0.00  10.99  0.00  0.00
127  1.52081  13.78  2.28  1.43  71.99  0.49   9.85  0.00  0.17
95   1.51860  13.36  3.43  1.43  72.26  0.51   8.60  0.00  0.00
..       ...    ...   ...   ...    ...   ...    ...   ...   ...
106  1.53125  10.73  0.00  2.10  69.81  0.58  13.30  3.15  0.28
14   1.51763  12.61  3.59  1.31  73.29  0.58   8.50  0.00  0.00
92   1.51588  13.12  3.41  1.58  73.26  0.07   8.39  0.00  0.19
179  1.51852  14.09  2.19  1.66  72.67  0.00   9.32  0.00  0.00
102  1.51820  12.62  2.76  0.83  73.81  0.35   9.42  0.00  0.20

[171 rows x 9 columns]

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\narendra tekale\anaconda3\lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [13]:
X_train

array([[-0.84623746, -0.74467528,  0.52636164, ..., -0.68807645,
        -0.33761134, -0.60110996],
       [ 0.28077633,  0.33413832,  0.54088841, ..., -0.03692037,
        -0.04564469,  1.78472688],
       [-0.0992632 ,  0.43938842, -2.03034913, ...,  1.44941417,
        -0.33761134, -0.60110996],
       ...,
       [-0.85278986, -0.34998738,  0.44646443, ..., -0.39080954,
        -0.33761134,  1.28767753],
       [ 0.0121277 ,  0.92617017, -0.43966828, ...,  0.26742432,
        -0.33761134, -0.60110996],
       [-0.09271079, -1.00780055, -0.02565546, ...,  0.33820216,
        -0.33761134,  1.3870874 ]])

In [14]:
svc = SVC()
svc.fit(X_train,y_train)

SVC()

In [16]:
y_pred = svc.predict(X_test)

In [17]:
accuracy_score(y_test,y_pred)

0.32558139534883723

## GridsearchCV

In [58]:
param_grid = {
    'C':[0.1,0.5,1.0,1.5],
    'kernel':['linear', 'poly','rbf'],
    'degree':[1,3,5,7],
    'shrinking':[True,False],
    'probability':[True,False]
}

In [59]:
param_grid

{'C': [0.1, 0.5, 1.0, 1.5],
 'kernel': ['linear', 'poly', 'rbf'],
 'degree': [1, 3, 5, 7],
 'shrinking': [True, False],
 'probability': [True, False]}

In [60]:
from sklearn.model_selection import GridSearchCV
svc_grid = GridSearchCV(estimator=svc,
           param_grid = param_grid,
           cv=5,
           n_jobs = -1)

In [61]:
svc_grid

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1.0, 1.5], 'degree': [1, 3, 5, 7],
                         'kernel': ['linear', 'poly', 'rbf'],
                         'probability': [True, False],
                         'shrinking': [True, False]})

In [62]:
svc_grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1.0, 1.5], 'degree': [1, 3, 5, 7],
                         'kernel': ['linear', 'poly', 'rbf'],
                         'probability': [True, False],
                         'shrinking': [True, False]})

In [63]:
svc_grid.best_params_

{'C': 1.0,
 'degree': 1,
 'kernel': 'rbf',
 'probability': True,
 'shrinking': True}

In [64]:
svc_grid.best_score_

0.6783193277310925