In [1]:
import pandas as pd
import numpy  as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [2]:
df= pd.read_csv('data/winequality-red.csv')

In [3]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
df.iloc[498]

fixed acidity           10.7000
volatile acidity         0.3500
citric acid              0.5300
residual sugar           2.6000
chlorides                0.0700
free sulfur dioxide      5.0000
total sulfur dioxide    16.0000
density                  0.9972
pH                       3.1500
sulphates                0.6500
alcohol                 11.0000
quality                  8.0000
Name: 498, dtype: float64

In [5]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [6]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [7]:
X = df.drop(columns=['quality'])
y = df['quality']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [9]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
772,9.5,0.570,0.27,2.30,0.082,23.0,144.0,0.99782,3.27,0.55,9.4
1170,9.2,0.360,0.34,1.60,0.062,5.0,12.0,0.99667,3.20,0.67,10.5
1595,5.9,0.550,0.10,2.20,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1261,6.3,1.020,0.00,2.00,0.083,17.0,24.0,0.99437,3.59,0.55,11.2
525,10.4,0.640,0.24,2.80,0.105,29.0,53.0,0.99980,3.24,0.67,9.9
...,...,...,...,...,...,...,...,...,...,...,...
1156,8.5,0.180,0.51,1.75,0.071,45.0,88.0,0.99524,3.33,0.76,11.8
487,10.2,0.645,0.36,1.80,0.053,5.0,14.0,0.99820,3.17,0.42,10.0
342,10.9,0.390,0.47,1.80,0.118,6.0,14.0,0.99820,3.30,0.75,9.8
1525,6.7,0.480,0.08,2.10,0.064,18.0,34.0,0.99552,3.33,0.64,9.7
478,9.6,0.680,0.24,2.20,0.087,5.0,28.0,0.99880,3.14,0.60,10.2

In [10]:
trf2 = ColumnTransformer([
    ('scaled',StandardScaler(),[0,1,2,3,4,5,6,7,8,9,10])
],remainder='passthrough')

In [11]:
trf2.fit_transform(X_train)

array([[ 0.68019047,  0.19534043,  0.00972094, ..., -0.26373634,
        -0.62204623, -0.94049003],
       [ 0.50752154, -0.95561903,  0.3649518 , ..., -0.70874792,
         0.07007828,  0.10439712],
       [-1.39183665,  0.08572525, -0.85298258, ...,  1.32559073,
         0.58917167,  0.7693253 ],
       ...,
       [ 1.48597879, -0.79119625,  1.02466625, ..., -0.07301709,
         0.53149463, -0.56053107],
       [-0.93138618, -0.29792791, -0.95447711, ...,  0.11770216,
        -0.10295285, -0.65552081],
       [ 0.73774678,  0.79822396, -0.14252086, ..., -1.09018641,
        -0.33366102, -0.1805721 ]])

In [12]:
trf3 = SVC()

In [13]:
pipe = Pipeline([
    ('trf2',trf2),
    ('trf3',trf3)
])

In [14]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaled', StandardScaler(),
                                                  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                   10])])),
                ('trf3', SVC())])

In [15]:
y_pred = pipe.predict(X_test)

In [16]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Model accuracy: {accuracy}")

Model accuracy: 0.63125

In [17]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

0.6043841911764706

In [18]:
import pickle
pickle.dump(pipe,open('70pipe.pkl','wb'))

In [19]:
param_grid = {
    'C':[0.1,0.5,1.0,1.5],
    'kernel':['linear', 'poly','rbf'],
    'degree':[1,3,5,7],
    'shrinking':[True,False],
    'probability':[True,False]
}

In [20]:
svc_grid = GridSearchCV(estimator=trf3,
           param_grid = param_grid,
           cv=5,
           n_jobs = -1)

In [21]:
svc_grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1.0, 1.5], 'degree': [1, 3, 5, 7],
                         'kernel': ['linear', 'poly', 'rbf'],
                         'probability': [True, False],
                         'shrinking': [True, False]})

In [22]:
svc_grid.best_params_

{'C': 0.5,
 'degree': 1,
 'kernel': 'linear',
 'probability': True,
 'shrinking': True}

In [23]:
svc_grid.best_score_

0.5809099264705881